angular.module('myApp',
    ['ui.router',
     'ngResource',
     'ng',
     'ngCookies',
     'ngAnimate',
     'ngFileUpload',
     'ngMaterial',
     'ngSanitize',
     'ngMessages',
     'pascalprecht.translate',
     'ui.bootstrap',
     'myApp.services',
     'myApp.controllers',
     'myApp.directives',
     'myApp.filters']);

angular.module('myApp.controllers',[]);
angular.module('myApp.services',[]);
angular.module('myApp.directives',[]);
angular.module('myApp.filters',[]);