application: coachersir-1045
version: 1
runtime: php55
api_version: 1
module: image-php-module

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /botr
  static_dir: botr

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js